### ISSUE TITLE
Typecase on tuple2 is throwing ClassCastException (1.11.3, 1.10.3. Scala 2.12.8)

### ISSUE THREAD

**Issue by gatorcse** [scodec/scodec#146]
I am trying to use the discriminator/typecase combinators on a tuple type. Example Code
```scala
import java.nio.charset.Charset

import scodec._
import scodec.bits._
import scodec.codecs._

implicit val defCharSet: Charset = Charset.defaultCharset()

// Simple, minimal ADT
sealed trait Foo
final case class Thing1(s: String) extends Foo
final case class Thing2(i: Int) extends Foo


// Codecs for the ADT
implicit val t1: Codec[Thing1] = string32.as[Thing1]
implicit val t2: Codec[Thing2] = int32.as[Thing2]

// Simple case where we are only discriminating the ADT, and this works.
val c1: Codec[Foo] = discriminated[Foo].by(uint(8))
  .typecase[Thing1](0x01, t1)
  .typecase[Thing2](0x02, t2)

val r1 = for {
  bits <- c1.encode(Thing2(1))
  res <- c1.decodeValue(bits)
} yield res // Successful(...)

// This will always try and match the first case, failing with ClassCastException
// if it isn't a `Thing1`.
val c2: Codec[(String, Foo)] = discriminated[(String, Foo)]
  .by(uint(8))
  .typecase[(String, Thing1)](0x01, cstring ~ t1)
  .typecase[(String, Thing2)](0x02, cstring ~ t2)

val r2 = for {
  bits <- c2.encode(("SomeVal", Thing2(2))) // throws
  res <- c2.decodeValue(bits)
} yield res

```

The first case, where we are only subclassing the `Foo` works just fine. The second case, where we are breaking apart a tuple will always match the first case, and then fail with ClassCastException. Stack trace:
```
java.lang.ClassCastException: Thing2 cannot be cast to Thing1
at anon$macro$4$1.to(<console>:25)
at scodec.Transformer$$anon$7.$anonfun$apply$12(Transform.scala:121)
at scodec.Codec$$anon$2.encode(Codec.scala:200)
at scodec.EncoderFunctions.$anonfun$encodeBoth$1(Encoder.scala:111)
at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
at scodec.EncoderFunctions.encodeBoth(Encoder.scala:110)
at scodec.EncoderFunctions.encodeBoth$(Encoder.scala:109)
at scodec.Codec$.encodeBoth(Codec.scala:460)
at scodec.codecs.TupleCodec.encode(TupleCodec.scala:12)
at scodec.codecs.TupleCodec.encode(TupleCodec.scala:6)
at scodec.codecs.DiscriminatorCodec.$anonfun$encode$3(DiscriminatorCodec.scala:349)
at scodec.Attempt$Successful.flatMap(Attempt.scala:113)
at scodec.codecs.DiscriminatorCodec.$anonfun$encode$2(DiscriminatorCodec.scala:349)
at scala.Option.map(Option.scala:163)
at scodec.codecs.DiscriminatorCodec.$anonfun$encode$1(DiscriminatorCodec.scala:347)
at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
at scala.collection.Iterator.toStream(Iterator.scala:1415)
at scala.collection.Iterator.toStream$(Iterator.scala:1414)
at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
at scodec.codecs.DiscriminatorCodec.encode(DiscriminatorCodec.scala:346)
... 38 elided
```

In [October of 2015](https://gitter.im/scodec/scodec?at=56284e7b6b0cea6a10119710), you answered a similar question on Gitter, and you recommended basically the same code. Latest version at that time would have been 1.8.2, and an older Scala.

**Comment by mpilquist** [comment]
It turns out this is an inherent restriction of `typecase` -- when encoding a value `a`, the generated codec effectively checks each registered type case in order via a `Class#isAssignableFrom` call, comparing the runtime class of the value `a` to the runtime class of the type case from the `ClassTag[R]` argument to `typecase`. Due to erasure, all parameterized types erase to the same runtime class. In this example, both cases erase to the `Tuple2` class.

I'll add some docs to the `typecase` method to make this restriction clearer. 

To fix this particular example, you can use `subcaseO` instead of `typecase`:

```scala
      val c: Codec[(String, Foo)] = discriminated[(String, Foo)]
        .by(uint(8))
        .subcaseO[(String, Thing1)](0x01) { case (s, t @ Thing1(_)) => Some((s, t)); case _ => None } (cstring ~ t1)
        .subcaseO[(String, Thing2)](0x02) { case (s, t @ Thing2(_)) => Some((s, t)); case _ => None } (cstring ~ t2)
```
