### ISSUE TITLE
Codec[EmptyTuple] has Iso to any product

### ISSUE THREAD

**Issue by kubukoz** [scodec/scodec#559]
When you have a `Codec[EmptyTuple]`, e.g. after a `dropUnits` done on a tuple of only-units, it can be `.as[...]`'d with any case class, causing a ClassCastException at runtime when the class actually has fields:

```scala
//> using dep org.scodec::scodec-core:2.3.2
import scodec.codecs.*
import scodec.bits.*

@main def demo = println(
  (constant[Int]() :: constant[Int]()).dropUnits.as[Foo].decode(BitVector.empty)
)

case class Foo(oops: String)
```

Result:

```
Exception in thread "main" java.lang.ClassCastException: class scala.Tuple$package$EmptyTuple$ cannot be cast to class scala.Tuple1 (scala.Tuple$package$EmptyTuple$ and scala.Tuple1 are in unnamed module of loader 'app')
        at scodec.Iso$.singleton$$anonfun$2(Iso.scala:92)
        at scodec.IsoLowPriority$$anon$2.from(Iso.scala:49)
        at scodec.Iso$$anon$1.to(Iso.scala:42)
        at scodec.Codec.as$$anonfun$1(Codec.scala:143)
        at scodec.DecodeResult.map(DecodeResult.scala:40)
        at scodec.Codec$$anon$2.decode$$anonfun$1(Codec.scala:157)
        at scodec.Attempt$Successful.map(Attempt.scala:128)
        at scodec.Codec$$anon$2.decode(Codec.scala:157)
        at main$package$.demo(main.scala:6)
        at demo.main(main.scala:5)
```

Tested in 2.3.2.

**Comment by kubukoz** [comment]
More minimal reproduction:

```scala
//> using dep org.scodec::scodec-core:2.3.2
import scodec.codecs.*
import scodec.bits.*
import scodec.Iso

@main def demo = summon[Iso[EmptyTuple, Tuple1[String]]].to(EmptyTuple)
```

**Comment by kubukoz** [comment]
I'm not sure this is actually scodec's fault...

even this compiles (and throws):

```scala
import scala.deriving.Mirror

@main def demo = {

  val m = summon[Mirror.ProductOf[EmptyTuple] { type MirroredElemTypes = Tuple1[String] }]

  Tuple.fromProductTyped(EmptyTuple)(
    using m
  ): Tuple1[String]
}
```

**Comment by kubukoz** [comment]
Reported upstream: https://github.com/scala/scala3/issues/22161
